## RANDOM FORESTS using only NumPy and Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("genre_df.csv", sep = '\t');
df.drop(["Unnamed: 0"], inplace = True, axis = 1)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1339 entries, 0 to 1338
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   danceability      1339 non-null   float64
 1   energy            1339 non-null   float64
 2   key               1339 non-null   int64  
 3   loudness          1339 non-null   float64
 4   mode              1339 non-null   int64  
 5   speechiness       1339 non-null   float64
 6   acousticness      1339 non-null   float64
 7   instrumentalness  1339 non-null   float64
 8   liveness          1339 non-null   float64
 9   valence           1339 non-null   float64
 10  tempo             1339 non-null   float64
 11  duration_ms       1339 non-null   int64  
 12  time_signature    1339 non-null   int64  
 13  track_name        1339 non-null   object 
 14  artist            1339 non-null   object 
 15  genre             1339 non-null   object 
dtypes: float64(9), int64(4), object(3)
memory 

In [4]:
df.drop(["artist", "track_name", "liveness"], axis = 1, inplace= True)

In [5]:
key_df = pd.get_dummies(df['key'], prefix='key')
df = pd.concat([df, key_df], axis = 1)
df.drop(['key', 'key_11'], axis = 1, inplace = True)

In [6]:
time_df = pd.get_dummies(df['time_signature'], prefix='time_signature')
df = pd.concat([df, time_df], axis = 1)
df.drop(['time_signature', 'time_signature_1'], axis = 1, inplace = True)

In [7]:
genre_dict = {'POP': 1, 'RAP': 2, 'CLASSICAL': 3, 'ROCK': 4, 'LOFI': 5}

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1339 entries, 0 to 1338
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   danceability      1339 non-null   float64
 1   energy            1339 non-null   float64
 2   loudness          1339 non-null   float64
 3   mode              1339 non-null   int64  
 4   speechiness       1339 non-null   float64
 5   acousticness      1339 non-null   float64
 6   instrumentalness  1339 non-null   float64
 7   valence           1339 non-null   float64
 8   tempo             1339 non-null   float64
 9   duration_ms       1339 non-null   int64  
 10  genre             1339 non-null   object 
 11  key_0             1339 non-null   uint8  
 12  key_1             1339 non-null   uint8  
 13  key_2             1339 non-null   uint8  
 14  key_3             1339 non-null   uint8  
 15  key_4             1339 non-null   uint8  
 16  key_5             1339 non-null   uint8  


In [9]:
import pandas as pd
import numpy as np

In [10]:
from sklearn.metrics import classification_report

In [11]:
from models import RandomForest

KeyboardInterrupt: 

In [ ]:
forest = RandomForest(n_estimators=6)

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop(['genre'], axis = 1)
y = df['genre']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [ ]:
forest.fit(X_train, y_train)

KeyboardInterrupt: 

In [ ]:
preds = forest.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, preds))
print(confusion_matrix(y_test, preds))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        14
  versicolor       0.92      1.00      0.96        12
   virginica       1.00      0.92      0.96        12

    accuracy                           0.97        38
   macro avg       0.97      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38

[[14  0  0]
 [ 0 12  0]
 [ 0  1 11]]
